version: '3.8'

services:
  reader:
    container_name: flow-reader-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "7127:7127"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=7127
      - HOSTNAME=0.0.0.0
      # Production URL for Synology NAS
      - NEXT_PUBLIC_WEBSITE_URL=http://anselmjeong.synology.me:7127
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7127/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: mount volume for persistent data
    # volumes:
    #   - reader_data:/app/data

# Optional: define named volumes
# volumes:
#   reader_data: 